COMPRESS_TARGET = compress
DECOMPRESS_TARGET = decompress

all: $(COMPRESS_TARGET) $(DECOMPRESS_TARGET)

clean:
	rm -rf $(COMPRESS_TARGET) $(DECOMPRESS_TARGET)

$(COMPRESS_TARGET): main.cpp
	g++ -O2 -DBUILD_COMPRESS -DPROGRAM_NAME="\"$(COMPRESS_TARGET)\"" main.cpp -o $(COMPRESS_TARGET)

$(DECOMPRESS_TARGET): main.cpp
	g++ -O2 main.cpp -DPROGRAM_NAME="\"$(DECOMPRESS_TARGET)\"" -o $(DECOMPRESS_TARGET)
